### ISSUE TITLE
🚀 Bug Alert! Shortened URL has Grown Taller Than Me 🙃

### ISSUE THREAD

**Issue by lukaswittmann** [FKammerer45/UrlShortenerServerless#1]
Hey there, fellow coders of the cosmos! I recently embarked on a journey to shorten my URLs with the magnificent UrlShortenerServerless, and, oh boy, what a wild ride it's been! 🎢

However, it seems that some of my super-duper long URLs have transformed into skyscrapers in disguise. 🌆 Now, I'm not the tallest person around, so I'd love some assistance making those URLs just a tad shorter.

🔍 Here's a short description of the issue:

When I try to shorten a lengthy URL, it comes out even longer! Is this a bug or a feature for future astronauts? 😄

Any chance we can turn this telescopic URL back into a pocket-sized link? Thanks for being the heroes of the coding universe! 🦸‍♂️🦸‍♀️

Cheers,
Lukas

**Comment by FKammerer45** [comment]
Hey Lukas! 🚀

First off, I absolutely love the enthusiasm and creativity in your message! It's always refreshing to see fellow coders of the cosmos bring such a vibrant energy to the table. 🌌

I'm glad you took the UrlShortenerServerless for a spin. However, I must admit, this project was primarily a training and educational endeavor for me to learn more about AWS and the wonders of JavaScript/HTML. It wasn't intended for production use, and I didn't get around to polishing it up to perfection.

That said, I genuinely appreciate you pointing out the "telescopic URL" issue. While it's not a feature for future astronauts (though that sounds like a fun idea 😄), it's definitely something I'll keep in mind if I ever decide to revisit and refine the project.

In the meantime, there are many fantastic URL shorteners out there that might better suit your needs. I hope you continue your coding adventures and find the perfect tool for your journey!

Thanks for being such a stellar part of the coding community. Keep reaching for the stars! 🌟

Warm regards,
Floo

**Comment by lukaswittmann** [comment]
Hi Floo! 🌟

Thank you for the cosmic response! Your creative project definitely caught my attention, and it's great to hear about your learning adventure with AWS and JavaScript. The "telescopic URL" quirk was just a fun part of the journey, and I appreciate your transparency about the project's scope. 😄

I'll keep exploring the universe of coding and find the perfect tool for my URL-shortening needs. Keep reaching for the stars in your coding adventures, too, and who knows, maybe we'll cross paths in the galaxy of code again someday! 🌌

By the way, have you ever thought about implementing this project in assembler? It could be an interesting challenge, and who knows what kind of cosmic URL shortening magic you might uncover in the process! 🚀

Wishing you all the best in your learning and coding endeavors.

Cheers,
Lukas 🚀
